### ISSUE TITLE
Unknown Timezone Error

### ISSUE THREAD

**Issue by michaelzdrav** [michaelzdrav/taskmate#24]
Upon reviewing logs, I could see an error about an unknown timezone 'Asia/Perth' with the error: `pytz.exceptions.UnknownTimeZoneError: 'Asia/Perth'`

<details><summary>Expand error</summary>
<p>

[2023-08-01 13:28:02,634] INFO in queries: Got timezone Asia/Perth for [tenant_id] 13, User [id] 13.
[2023-08-01 13:28:02,634] INFO in landing: Got tenancy timezone Asia/Perth.
[2023-08-01 13:28:06,147] ERROR in app: Exception on /mobile/15 [GET]
Traceback (most recent call last):
  File "/run/venv/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/run/venv/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/run/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/run/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/run/web/landing.py", line 122, in task_view
    return render_template(
  File "/run/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/run/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/run/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/run/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/run/web/Templates/mobile/task.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/run/web/Templates/base.html", line 125, in top-level template code
    {% block header %}{% endblock %}
  File "/run/web/Templates/mobile/task.html", line 76, in block 'header'
    <td>{{ view.created.strftime("%Y-%m-%d %H:%M:%S") | convert_utc_to_timezone }}</td>
  File "/run/web/__init__.py", line 25, in convert_utc_to_timezone
    user_timezone = pytz.timezone(session["timezone"])
  File "/run/venv/lib/python3.8/site-packages/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'Asia/Perth'

</p>
</details>

**Comment by michaelzdrav** [comment]
Fixed in the commit d5f7c13aeb698fb6b59f0e9f88a1fdedfc8d7dc6
Issue was an incorrect timezone in [timezones.py](web/timezones.py)
